on: [push, pull_request]

jobs:
  build-linux:
    strategy:
      matrix:
        target:
          - arch: i386
            triplet: i686-unknown-linux-gnu
            qualifier: x86_32
          - arch: amd64
            triplet: x86_64-unknown-linux-gnu
            qualifier: x86_64
          - arch: armhf
            triplet: armv7-unknown-linux-gnueabihf
            qualifier: armv7
          - arch: arm64
            triplet: aarch64-unknown-linux-gnu
            qualifier: aarch64
          - arch: ppc64el
            triplet: powerpc64le-unknown-linux-gnu
            qualifier: ppc64el
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build project and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          context: .
          build-args: |
            BUILD_ARCH=${{ matrix.target.arch }}
            RUST_TRIPLET=${{ matrix.target.triplet }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cix:${{ matrix.target.triplet }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Copy executable from Docker image to host
        run: |
          id=$(docker ps -q | xargs)
          build_path=$(\
            docker exec $id ls -R / | \
            grep "cix/target/${{ matrix.target.triplet }}/debug:" | \
            sed -e "s/:.*//" \
          )
          docker cp "$id:$build_path/cix" "hello-${{ matrix.target.qualifier }}"
      - name: Upload artifact for linux-${{ matrix.target.qualifier }}
        uses: actions/upload-artifact@v3
        with:
          name: hello-${{ matrix.target.qualifier }}-linux
          path: hello-${{ matrix.target.qualifier }}
  build-windows:
    strategy:
      matrix:
        target:
          - triplet: x86_64-pc-windows-gnu
            qualifier: x86_64
            gcc: gcc-mingw-w64-x86-64
          - triplet: i686-pc-windows-gnu
            qualifier: x86_32
            gcc: gcc-mingw-w64-i686
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target.triplet }}
      - name: Install GCC MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.target.gcc }}
      - name: Build project
        run: |
          printf "\
          [build] \n\
          rustflags = [\"-C\", \"embed-bitcode=off\"] \n\
          [profile.dev] \n\
          lto = \"off\" \
          " > $HOME/.cargo/config
          cargo build --target ${{ matrix.target.triplet }}
      - name: Upload artifact for windows-${{ matrix.target.qualifier }}
        uses: actions/upload-artifact@v3
        with:
          name: cix-${{ matrix.target.qualifier }}-windows
          path: target/${{ matrix.target.triplet }}/debug/cix.exe
