on: [push]

name: Build

jobs:
  build:
    strategy:
      matrix:
        target:
          - triplet: x86_64-unknown-linux-gnu
            build: cix
            artifact: cix-x86_64-linux
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target.triplet }}
          override: true
      - name: Compile project
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target.triplet }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target.artifact }}
          path: target/${{ matrix.target.triplet }}/debug/${{ matrix.target.build }}
